### ISSUE TITLE
此即時路況影像APP 被當廣告阻擋

### ISSUE THREAD

**Issue by kai456789** [FutaGuard/Public-DNS#2]
此即時路況影像APP 被當廣告阻擋
進不去APP主畫面 關閉DNS即正常 能設白名單嗎 謝謝

https://play.google.com/store/apps/details?id=app.doitwell.cctvs&hl=zh_TW&gl=US

**Comment by tasi788** [comment]
我今天研究一下

**Comment by tasi788** [comment]
可能沒辦法，他是偵測無法打開 google 廣告就會不開啟 app
我不能針對特定 app 設定白名單，請你在裝置上游設定白名單

**Comment by kai456789** [comment]
好的 感謝辛苦處理 該作者的回應 也是不愛廣告 請刪除APP

**Comment by tasi788** [comment]
> 好的 感謝辛苦處理 該作者的回應 也是不愛廣告 請刪除APP

笑死 太兇了吧
